### PR TITLE
[WIP] : Added L2MarginLoss

### LINKED ISSUE #44: L2MarginLoss
The margin formulation of the least squares loss. Pretty much the L2HingeLoss but not truncated at `agreement >= 1`. Not the most interesting loss, but for completeness sake it would be nice to have it in here. (see p. 35, example 2.26 in Steinwart 2008)
- Steinwart, Ingo, and Andreas Christmann. Support vector machines. Springer Science & Business Media, 2008.

### PR DESCRIPTION
**Pull request by kumarkrishna**
Adding L2MarginLoss to LossFunctions
Fixes #44.

### CODE REVIEW

**Comment by Evizero** [comment]
Hi! Thanks for the contribution. I can't merge, though, without the corresponding tests in place. But I can give some pointers at how to go about them

Could you add the new loss here:

- https://github.com/JuliaML/LossFunctions.jl/blob/master/test/tst_loss.jl#L221

- https://github.com/JuliaML/LossFunctions.jl/blob/master/test/tst_loss.jl#L351

And adapt the following tests for the new loss:

- https://github.com/JuliaML/LossFunctions.jl/blob/master/test/tst_loss.jl#L255-L256

- https://github.com/JuliaML/LossFunctions.jl/blob/master/test/tst_properties.jl#L457-L483

**Comment by Evizero** [comment]
Thanks!

**Comment by kumarkrishna** [comment]
Hi! I've put the basic tests in place. As for the unicode plots in the doc-string I am looking into [UnicodePlots.jl](https://github.com/Evizero/UnicodePlots.jl), and we could merge after adding that?

**Comment by Evizero** [comment]
The little plots are a little custom tailored and not straight forward. I will take care of it and the docs

**Comment by kumarkrishna** [comment]
Sure! :)

**Pull request merged**
