### PR TITLE
Add loss-properties documentation.

### LINKED ISSUE #73: Documentation of Loss properties
It would maybe be nice to describe the implemented properties. For example the description for `isconvex` could state a short formal or informal definition for what makes a loss convex. etc

*note to self: link to places. add reference in contributing issue*

### PR DESCRIPTION
**Pull request by kumarkrishna**
Completes #74 and fixes #73 .

### CODE REVIEW

**Comment by Evizero** [comment]
very nice! I think we will have a merge conflict though because just half an other ago I made some changes to the convex documentation. I just pushed that. Could you maybe look into fixing the conflict on your end? Basically what I changed is some typing and I added the reference to the Boyd book from which the definition seems to be taken out of

**Comment by Evizero** [comment]
actually I'll look into it right now

**Comment by Evizero** [comment]
Ok, thanks! I rebased your new commits and added them to the `dev` branch (so they are already merged now and I will close this PR).

**Comment by Evizero** [comment]
There seem to be some type-setting issues (which I may have introduced in the process). I'll take care of them. thanks again

**Comment by kumarkrishna** [comment]
Thanks! I've taken some definitions from the Steinwart book too, so it would probably be a good idea to put in a reference. Also, ```isclasscalibrated``` has a slightly more involved documentation, so I'll add that today and cover all the properties.

**Comment by Evizero** [comment]
I just pushed my changes to the properties to the dev branch. http://lossesjl.readthedocs.io/en/dev/losses/interface.html#properties-of-a-loss. mostly type-setting fixes, and some notation simplification

**Pull request closed without merging**
